### ISSUE TITLE
Job ErrorError occurred while processing job:

### ISSUE THREAD

**Issue by kusakci** [Merck/Mutation_Maker#17]
Hi, 

Thank you for this platform. I am running the mutation maker on a local host. 

And I want to work on individual modules of the platform.  However, I have several questions to ask:

1- How do you work on and test individual modules of this platform. If we want to add new features to it, can we directly test the changes through the frontend after writing a backend code? This was a general question. I tried running the code both on ubuntu and on windows.

2 - I used the sample entry as below in SSM module:
  
Plasmid: GGAGTCAGCTCATTGTTGGCGTGGACACCACAACAGGCGACGTAGGAACGAGCCCCGACCTGGGACTGAGCTGGGGATACGAAACAGCTGCGAGCGGCGAAACCCTGTACGGCATTGATATTTCGAAAGATGGAAGCAAAATCACCGCATGCGCATTCGGCGGGCACATCTGGACTAAATCGGGAGGGCTGTGGACCTCCAGAGATATCGCTCGTAATTGGTTTCGTAATAAGATGAGCGCCAATGGGGTCATCCAGGTCGCCATCGTATATGGTGGATATGTGTACGTCTCCACGGATTCAGGGGCAACCTGGACGCCATGCCTGGGCGCTTCTCCGCCTGGCGTGGCCGGAGTAGCAGACTGGCATGGGGTTGACATAAGCGCGGATGGGACAAAAATTGTAGTGTGCGCATATACAGGGGGTGGCTTGTGGCGTTCCGACGACTCTGGTGCGACATGGGCCTCTTTGGGCACACCGTCTGGACCTAACCCAGCGGATGTCGCAATTTCGAATGACGGCGTGTATATTACGATTTGCGGCGCGGGTCCGGGTCAGTGTTATTCAAGTCAGGATTCTGGCGCTACCTTTGGGATTTTCTCCACTATTGCAGACGCATGGTTAGGTGTTAAGATGTCAGATTCGGGACAGTATCAAACTGCCATTGGTTACTCCGCTCCAAATATTGCCTGGGGAGTCTTCTCTATCAACTATGGCGTGACATCGTTCGCCGTAACATTTGATACGGGCCCACTGGGAACTCCTTGCGATGTTACGATGAACGATGATGGTACCATTCAGTTTTGCGGCTTTTATGGTGGTCCTGTGTATAAGTCAGTAGATTATGGCGCTAATTTTATTAAACAGGTATTAGATGCGAATGTATTCGGGGCAATAGCCATATCTGAGCCTCTGCTTCTTCATGAAATTACACAAGCTATTTTTATACTCGAGCACCACCACCACCACCACTGAGATCCGGCTGCTAACAAAGCCCGAAAGGAAGCTGAGTTGGCTGCTGCCACCGCTGAGCAATAACTAGCATAACCCCTTGGGGCCTCTAAACGGGTCTTGAGGGGTTTTTTGCTGAAAGGAGGAACTATATCCGGATTGGCGAATGGGACGCGCCCTGTAGCGGCGCATTAAGCGCGGCGGGTGTGGTGGTTACGCGCAGCGTGACCGCTACACTTGCCAGCGCCCTAGCGCCCGCTCCTTTCGCTTTCTTCCCTTCCTTTCTCGCCACGTTCGCCGGCTTTCCCCGTCAAGCTCTAAATCGGGGGCTCCCTTTAGGGTTCCGATTTAGTGCTTTACGGCACCTCGACCCCAAAAAACTTGATTAGGGTGATGGTTCACGTAGTGGGCCATCGCCCTGATAGACGGTTTTTCGCCCTTTGACGTTGGAGTCCACGTTCTTTAATAGTGGACTCTTGTTCCAAACTGGAACAACACTCAACCCTATCTCGGTCTATTCTTTTGATTTATAAGGGATTTTGCCGATTTCGGCCTATTGGTTAAAAAATGAGCTGATTTAACAAAAATTTAACGCGAATTTTAACAAAATATTAACGCTTACAATTTAGGTGGCACTTTTCGGGGAAATGTGCGCGGAACCCCTATTTGTTTATTTTTCTAAATACATTCAAATATGTATCCGCTCATGAATTAATTCTTAGAAAAACTCATCGAGCATCAAATGAAACTGCAATTTATTCATATCAGGATTATCAATACCATATTTTTGAAAAAGCCGTTTCTGTAATGAAGGAGAAAACTCACCGAGGCAGTTCCATAGGATGGCAAGATCCTGGTATCGGTCTGCGATTCCGACTCGTCCAACATCAATACAACCTATTAATTTCCCCTCGTCAAAAATAAGGTTATCAAGTGAGAAATCACCATGAGTGACGACTGAATCCGGTGAGAATGGCAAAAGTTTATGCATTTCTTTCCAGACTTGTTCAACAGGCCAGCCATTACGCTCGTCATCAAAATCACTCGCATCAACCAAACCGTTATTCATTCGTGATTGCGCCTGAGCGAGACGAAATACGCGATCGCTGTTAAAAGGACAATTACAAACAGGAATCGAATGCAACCGGCGCAGGAACACTGCCAGCGCATCAACAATATTTTCACCTGAATCAGGATATTCTTCTAATACCTGGAATGCTGTTTTCCCGGGGATCGCAGTGGTGAGTAACCATGCATCATCAGGAGTACGGATAAAATGCTTGATGGTCGGAAGAGGCATAAATTCCGTCAGCCAGTTTAGTCTGACCATCTCATCTGTAACATCATTGGCAACGCTACCTTTGCCATGTTTCAGAAACAACTCTGGCGCATCGGGCTTCCCATACAATCGATAGATTGTCGCACCTGATTGCCCGACATTATCGCGAGCCCATTTATACCCATATAAATCAGCATCCATGTTGGAATTTAATCGCGGCCTAGAGCAAGACGTTTCCCGTTGAATATGGCTCATAACACCCCTTGTATTACTGTTTATGTAAGCAGACAGTTTTATTGTTCATGACCAAAATCCCTTAACGTGAGTTTTCGTTCCACTGAGCGTCAGACCCCGTAGAAAAGATCAAAGGATCTTCTTGAGATCCTTTTTTTCTGCGCGTAATCTGCTGCTTGCAAACAAAAAAACCACCGCTACCAGCGGTGGTTTGTTTGCCGGATCAAGAGCTACCAACTCTTTTTCCGAAGGTAACTGGCTTCAGCAGAGCGCAGATACCAAATACTGTCCTTCTAGTGTAGCCGTAGTTAGGCCACCACTTCAAGAACTCTGTAGCACCGCCTACATACCTCGCTCTGCTAATCCTGTTACCAGTGGCTGCTGCCAGTGGCGATAAGTCGTGTCTTACCGGGTTGGACTCAAGACGATAGTTACCGGATAAGGCGCAGCGGTCGGGCTGAACGGGGGGTTCGTGCACACAGCCCAGCTTGGAGCGAACGACCTACACCGAACTGAGATACCTACAGCGTGAGCTATGAGAAAGCGCCACGCTTCCCGAAGGGAGAAAGGCGGACAGGTATCCGGTAAGCGGCAGGGTCGGAACAGGAGAGCGCACGAGGGAGCTTCCAGGGGGAAACGCCTGGTATCTTTATAGTCCTGTCGGGTTTCGCCACCTCTGACTTGAGCGTCGATTTTTGTGATGCTCGTCAGGGGGGCGGAGCCTATGGAAAAACGCCAGCAACGCGGCCTTTTTACGGTTCCTGGCCTTTTGCTGGCCTTTTGCTCACATGTTCTTTCCTGCGTTATCCCCTGATTCTGTGGATAACCGTATTACCGCCTTTGAGTGAGCTGATACCGCTCGCCGCAGCCGAACGACCGAGCGCAGCGAGTCAGTGAGCGAGGAAGCGGAAGAGCGCCTGATGCGGTATTTTCTCCTTACGCATCTGTGCGGTATTTCACACCGCAATGGTGCACTCTCAGTACAATCTGCTCTGATGCCGCATAGTTAAGCCAGTATACACTCCGCTATCGCTACGTGACTGGGTCATGGCTGCGCCCCGACACCCGCCAACACCCGCTGACGCGCCCTGACGGGCTTGTCTGCTCCCGGCATCCGCTTACAGACAAGCTGTGACCGTCTCCGGGAGCTGCATGTGTCAGAGGTTTTCACCGTCATCACCGAAACGCGCGAGGCAGCTGCGGTAAAGCTCATCAGCGTGGTCGTGAAGCGATTCACAGATGTCTGCCTGTTCATCCGCGTCCAGCTCGTTGAGTTTCTCCAGAAGCGTTAATGTCTGGCTTCTGATAAAGCGGGCCATGTTAAGGGCGGTTTTTTCCTGTTTGGTCACTGATGCCTCCGTGTAAGGGGGATTTCTGTTCATGGGGGTAATGATACCGATGAAACGAGAGAGGATGCTCACGATACGGGTTACTGATGATGAACATGCCCGGTTACTGGAACGTTGTGAGGGTAAACAACTGGCGGTATGGATGCGGCGGGACCAGAGAAAAATCACTCAGGGTCAATGCCAGCGCTTCGTTAATACAGATGTAGGTGTTCCACAGGGTAGCCAGCAGCATCCTGCGATGCAGATCCGGAACATAATGGTGCAGGGCGCTGACTTCCGCGTTTCCAGACTTTACGAAACACGGAAACCGAAGACCATTCATGTTGTTGCTCAGGTCGCAGACGTTTTGCAGCAGCAGTCGCTTCACGTTCGCTCGCGTATCGGTGATTCATTCTGCTAACCAGTAAGGCAACCCCGCCAGCCTAGCCGGGTCCTCAACGACAGGAGCACGATCATGCGCACCCGTGGGGCCGCCATGCCGGCGATAATGGCCTGCTTCTCGCCGAAACGTTTGGTGGCGGGACCAGTGACGAAGGCTTGAGCGAGGGCGTGCAAGATTCCGAATACCGCAAGCGACAGGCCGATCATCGTCGCGCTCCAGCGAAAGCGGTCCTCGCCGAAAATGACCCAGAGCGCTGCCGGCACCTGTCCTACGAGTTGCATGATAAAGAAGACAGTCATAAGTGCGGCGACGATAGTCATGCCCCGCGCCCACCGGAAGGAGCTGACTGGGTTGAAGGCTCTCAAGGGCATCGGTCGAGATCCCGGTGCCTAATGAGTGAGCTAACTTACATTAATTGCGTTGCGCTCACTGCCCGCTTTCCAGTCGGGAAACCTGTCGTGCCAGCTGCATTAATGAATCGGCCAACGCGCGGGGAGAGGCGGTTTGCGTATTGGGCGCCAGGGTGGTTTTTCTTTTCACCAGTGAGACGGGCAACAGCTGATTGCCCTTCACCGCCTGGCCCTGAGAGAGTTGCAGCAAGCGGTCCACGCTGGTTTGCCCCAGCAGGCGAAAATCCTGTTTGATGGTGGTTAACGGCGGGATATAACATGAGCTGTCTTCGGTATCGTCGTATCCCACTACCGAGATATCCGCACCAACGCGCAGCCCGGACTCGGTAATGGCGCGCATTGCGCCCAGCGCCATCTGATCGTTGGCAACCAGCATCGCAGTGGGAACGATGCCCTCATTCAGCATTTGCATGGTTTGTTGAAAACCGGACATGGCACTCCAGTCGCCTTCCCGTTCCGCTATCGGCTGAATTTGATTGCGAGTGAGATATTTATGCCAGCCAGCCAGACGCAGACGCGCCGAGACAGAACTTAATGGGCCCGCTAACAGCGCGATTTGCTGGTGACCCAATGCGACCAGATGCTCCACGCCCAGTCGCGTACCGTCTTCATGGGAGAAAATAATACTGTTGATGGGTGTCTGGTCAGAGACATCAAGAAATAACGCCGGAACATTAGTGCAGGCAGCTTCCACAGCAATGGCATCCTGGTCATCCAGCGGATAGTTAATGATCAGCCCACTGACGCGTTGCGCGAGAAGATTGTGCACCGCCGCTTTACAGGCTTCGACGCCGCTTCGTTCTACCATCGACACCACCACGCTGGCACCCAGTTGATCGGCGCGAGATTTAATCGCCGCGACAATTTGCGACGGCGCGTGCAGGGCCAGACTGGAGGTGGCAACGCCAATCAGCAACGACTGTTTGCCCGCCAGTTGTTGTGCCACGCGGTTGGGAATGTAATTCAGCTCCGCCATCGCCGCTTCCACTTTTTCCCGCGTTTTCGCAGAAACGTGGCTGGCCTGGTTCACCACGCGGGAAACGGTCTGATAAGAGACACCGGCATACTCTGCGACATCGTATAACGTTACTGGTTTCACATTCACCACCCTGAATTGACTCTCTTCCGGGCGCTATCATGCCATACCGCGAAAGGTTTTGCGCCATTCGATGGTGTCCGGGATCTCGACGCTCTCCCTTATGCGACTCCTGCATTAGGAAGCAGCCCAGTAGTAGGTTGAGGCCGTTGAGCACCGCCGCCGCAAGGAATGGTGCATGCAAGGAGATGGCGCCCAACAGTCCCCCGGCCACGGGGCCTGCCACCATACCCACGCCGAAACAAGCGCTCATGAGCCCGAAGTGGCGAGCCCGATCTTCCCCATCGGTGATGTCGGCGATATAGGCGCCAGCAACCGCACCTGTGGCGCCGGTGATGCCGGCCACGATGCGTCCGGCGTAGAGGATCGAGATCTCGATCCCGCGAAATTAATACGACTCACTATAGGGGAATTGTGAGCGGATAACAATTCCCCTCTAGAAATAATTTTGTTTAACTTTAAGAAGGAGATATACCATGG

Gene of Interest: 
ATGGGGTTGACATAAGCGCGGATGGGACAAAAATTGTAGTGTGCGCATATACAGGGGGTGGCTTGTGGCGTTCCGACGACTCTGGTGCGACATGGGCCTCTTTGGGCACACCGTCTGGACCTAACCCAGCGGATGTCGCAATTTCGAATGACGGCGTGTATATTACGATTTGCGGCGCGGGTCCGGGTCAGTGTTATTCAAGTCAGGATTCTGGCGCTACCTTTGGGATTTTCTCCACTATTGCAGACGCATGGTTAGGTGTTAAGATGTCAGATTCGGGACAGTATCAAACTGCCATTGGTTACTCCGCTCCAAATATTGCCTGGGGAGTCTTCTCTATCAACTATGGCGTGACATCGTTCGCCGTAACATTTGATACGGGCCCACTGGGAACTCCTTGCGATGTTACGATGAACGATGATGGTACCATTCAGTTTTGCGGCTTTTATGGTGGTCCTGTGTATAAGTCAGTAGATTATGGCGCTAATTTTATTAAACAGGTATTAGATGCGAATGTATTCGGGGCAATAGCCATATCTGAGCCTCTGCTTCTTCATGAAATTACACAAGCTATTTTTATACTCGAGCACCACCACCACCACCACTGAGATCCGGCTGCTAACAAAGCCCGAAAGGAAGCTGAGTTGGCTGCTGCCACCGCTGAGCAATAACTAGCATAACCCCTTGGGGCCTCTAAACGGGTCTTGAGGGGTTTTTTGCTGAAAGGAGGAACTATATCCGGATTGGCGAATGGGACGCGCCCTGTAGCGGCGCATTAAGCGCGGCGGGTGTGGTGGTTACGCGCAGCGTGACCGCTACACTTGCCAGCGCCCTAGCGCCCGCTCCTTTCGCTTTCTTCCCTTCCTTTCTCGCCACGTTCGCCGGCTTTCCCCGTCAAGCTCTAAATCGGGGGCTCCCTTTAGGGTTCCGATTTAG

Mutations; 
K11N

Then I chose custom for the primers and entered :

Forward Primer
ATGGGGTTGACATAAGCGCGGATGGGACAA
Reverse Primer
CACAAGCCACCCCCTGTATATGCGCACACTACAA

The platform gave me an error:

Job ErrorError occurred while processing job: Traceback (most recent call last): File "/usr/local/lib/python3.7/site-packages/celery/app/trace.py", line 385, in trace_task R = retval = fun(*args, **kwargs) File "/usr/local/lib/python3.7/site-packages/celery/app/trace.py", line 648, in __protected_call__ return self.run(*args, **kwargs) File "/mutation_maker/tasks.py", line 52, in ssm return ssm_solve(input, main_generator, secondary_generator) File "/mutation_maker/mutation_maker/ssm.py", line 64, in ssm_solve result = solver.solve_for_mutations_faster(mutations) File "/mutation_maker/mutation_maker/ssm.py", line 261, in solve_for_mutations_faster self.temp_calculator) File "/mutation_maker/mutation_maker/ssm_fast_approximation.py", line 126, in grow_primers overlap, rw_temp_threshold, temp_calculator)) File "/mutation_maker/mutation_maker/ssm_fast_approximation.py", line 108, in grow_reverse_primer return SSMPrimerSpec(offset, overlap_end - offset, mutation.position - offset, rw_three_end_temp) UnboundLocalError: local variable 'offset' referenced before assignment

Any hint why do I see this error?

Thanks again,

Emre

**Comment by ra100** [comment]
First, I'm sorry for late response (we don't have worktime allocated for this anymore, so I'll have to find some personal time for this :))

Testing, there are separate tests for backend: https://github.com/Merck/Mutation_Maker/tree/master/backend/tests/unit_tests for each modules. So if there would be some feature development/fix, the case would be good to be added there.
Otherwise for "playing/trying" you can just go through UI. And Frontend is almost untested by automated tests.

Finally, the reported issue. I'll have to run that locally and see what that issue is about. It almost looks like error in the code `UnboundLocalError: local variable 'offset' referenced before assignment`, but then it should be failing for anything in SSM.

Can you try running it without "fast" mode?
